dataset:
  train:
    class: RAGBatchWrapper
    dataset:
      class: MoleculeDataset
      mmap_dir: ./datasets/molecule/CrossDocked/processed
      specify_index: ./datasets/molecule/CrossDocked/processed/train_index.txt
      length_type: atom
    rag_map_path: ./datasets/molecule/CrossDocked/rag_map.train.jsonl
  valid:
    class: RAGBatchWrapper
    dataset:
      class: MoleculeDataset
      mmap_dir: ./datasets/molecule/CrossDocked/processed
      specify_index: ./datasets/molecule/CrossDocked/processed/valid_index.txt
      length_type: atom
    rag_map_path: ./datasets/molecule/CrossDocked/rag_map.valid.jsonl

dataloader:
  train:
    batch_size: 8
    shuffle: true
    num_workers: 8
  valid:
    batch_size: 8
    num_workers: 8

trainer:
  class: IterAETrainer
  criterion: loss
  config:
    max_epoch: 50
    save_topk: 5
    val_freq: 2
    save_dir: ./ckpts/unimomo_rag_mol
    grad_clip: 1.0
    patience: 10
    warmup: 2000
    metric_min_better: true
    logger: tensorboard
    optimizer:
      class: AdamW
      lr: 1.0e-4
    scheduler:
      class: ReduceLROnPlateau
      factor: 0.8
      patience: 5
      mode: min
      frequency: val_epoch
      min_lr: 5.0e-6

model:
  class: CondIterAutoEncoder
  encoder_type: EPT
  decoder_type: EPT
  embed_size: 512
  hidden_size: 512
  latent_size: 8
  edge_size: 64
  k_neighbors: 9
  encoder_opt:
    n_rbf: 64
    cutoff: 10.0
    n_layers: 6
    n_head: 8
    use_edge_feat: true
    pre_norm: true
    efficient: false
    vector_act: layernorm
  decoder_opt:
    n_rbf: 64
    cutoff: 10.0
    n_layers: 6
    n_head: 8
    use_edge_feat: true
    pre_norm: true
    efficient: false
    vector_act: layernorm
  loss_weights:
    Zh_kl_loss: 0.6
    Zx_kl_loss: 0.8
    atom_coord_loss: 1.0
    block_type_loss: 1.0
    contrastive_loss: 0.0
    local_distance_loss: 0.5
    bond_loss: 0.5
    bond_length_loss: 0.0
    rag_contrastive_loss: 0.1
  prior_coord_std: 1.0
  coord_noise_scale: 1.0
  pocket_mask_ratio: 0.05
  decode_mask_ratio: 0.0
  kl_on_pocket: false
  discrete_timestep: false
  rag_opt:
    subgraph_index: ./datasets/molecule/CrossDocked/subgraphs.jsonl
    hidden_size: 512
    num_layers: 3
    temperature: 0.07
    negatives_per_pos: 8
    readout: mean

load_ckpt: ''

